rclone = "/Users/brechtm/.nix-profile/bin/rclone"
bwlimit = "400K"
keep_all = "7 days"
keep_daily = "31 days"

[brechtm]
source = "/Users/brechtm"
destination = "crypt:Backup/MacBook/Users/brechtm"
interval = "6 hours"
threshold = "10 KB"

[brechtm_Library]
source = "/Users/brechtm/Library"
destination = "crypt:Backup/MacBook/Users/brechtm_Library"
interval = "2 days"
threshold = "10 MB"
